name: 'Setup premake'
description: 'GitHub action to setup premake on Linux, Windows and MacOS.'
inputs:
  version:
    description: 'Premake version'
    required: true
branding:
  icon: 'box'
  color: 'red'
runs:
  using: 'node16'
  main: 'index.js'