name: MSBuild

on: [ push, pull_request ]

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
    
    - name: Setup premake
      uses: ./
      with:
        version: 5.0.0-beta2

    - run: premake5 --version

    - run: mkdir subdir

    - working-directory: subdir
      run: premake5 --version