name: MSBuild

on: [ push, pull_request ]

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: abel0b/setup-premake@v2.2
        with:
          version: "5.0.0-beta2"
      - name: Premake5 generated
        run:
          premake5 gmake2
      - name: Build Tsukasa Tsukuyomi bot
        run:
          make config=release build
      - name: Run Tsukasa Tsukuyomi bot
        run: |
          cd build/build
          ./Tsukasa-Tsukuyomi